### ISSUE TITLE
A "cherry-pick" quarkus application is failing with kafka "auto-serializers" enabled

### ISSUE THREAD

**Issue by pjgg** [quarkus-qe/quarkus-test-framework#278]
Given a Quarkus application as the follow one:
```
@QuarkusApplication //(classes = { SlowTopicConsumer.class, SlowTopicResource.class })
static RestService app = new RestService()
            .withProperty("kafka.bootstrap.servers", kafka::getBootstrapUrl)
            .withProperty("quarkus.kafka-streams.bootstrap-servers", kafka::getBootstrapUrl)
```

Fails with message:
```
 Unable to create the publisher or subscriber during initialization: java.lang.IllegalArgumentException: The attribute `value.deserializer` on connector 'smallrye-kafka' (channel: login-denied) must be set
```

Reproducer: https://github.com/quarkus-qe/quarkus-test-suite/blob/main/messaging/kafka-streams-reactive-messaging/src/test/java/io/quarkus/ts/messaging/kafka/KafkaGratefulShutdownIT.java#L36

Note: in the above reproducer you need to remove the serializer from `RestService app`

**Comment by Sgitario** [comment]
This is not an issue of the test framework: the following properties:

{code}
mp.messaging.outgoing.login-http-response-values.connector=smallrye-kafka

mp.messaging.incoming.login-denied.connector=smallrye-kafka
mp.messaging.incoming.login-denied.enable.auto.commit=true
{code}

These are present in the `application.properties` file and hence the KafkaConnectorOutgoingConfiguration is called for those which throws an exception because the `value.serializer` (and the deserializer) are not set.

I'm not sure if this should be reported in Quarkus though as this exception should not be thrown ever (as defaults will be used).

**Comment by pjgg** [comment]
The no scenario related `outgoing` or `incoming` properties that are located on `application.properties` are making this error. So is more a configuration error rather than a FW issue.
