### ISSUE TITLE
Feature: Don't scale down OpenShift resources if required

### ISSUE THREAD

**Issue by kshpak** [quarkus-qe/quarkus-test-framework#342]
To be able to investigate what happened with OpenShift scenario and its services it will be handy to leave resources untouched after the test has been executed (e.x. if the test failed and we want to see pod logs)

Currently, we have only property `-Dts.openshift.delete.project.after.all=false` which won't remove resources, however, it will scale them down.

Implementation ideas: the new property can be introduced which will be used along with `-Dts.openshift.delete.project.after.all=false`. Because some modules contain more than one OpenShift test we can't bind property `-Dts.openshift.delete.project.after.all=false` to do both (not delete + not scale down) (I guess)

**Comment by pjgg** [comment]
By default, all resources (remote or local) are going to be removed. Only if you are debugging some scenarios you will enable this property:

```
-Dts.openshift.delete.project.after.all=true
```

In my opinion, this property should apply to all resources, so should not scale down if is enabled. 
You should combine the above property with  `ephemeral.namespaces` disable in order to then later be able to remove the remote/local resources by hand

```
-Dts.openshift.ephemeral.namespaces.enabled=false
``` 

after your debugging effort, remove all your remote resources by hand

```
oc delete -n <YOUR_NAME_SPACE> --all all
```
